// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.24.4
// source: internal-master.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTabletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabletAddress string `protobuf:"bytes,1,opt,name=tablet_address,json=tabletAddress,proto3" json:"tablet_address,omitempty"`
}

func (x *RegisterTabletRequest) Reset() {
	*x = RegisterTabletRequest{}
	mi := &file_internal_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTabletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTabletRequest) ProtoMessage() {}

func (x *RegisterTabletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTabletRequest.ProtoReflect.Descriptor instead.
func (*RegisterTabletRequest) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTabletRequest) GetTabletAddress() string {
	if x != nil {
		return x.TabletAddress
	}
	return ""
}

type RegisterTabletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterTabletResponse) Reset() {
	*x = RegisterTabletResponse{}
	mi := &file_internal_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTabletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTabletResponse) ProtoMessage() {}

func (x *RegisterTabletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTabletResponse.ProtoReflect.Descriptor instead.
func (*RegisterTabletResponse) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{1}
}

type UnregisterTabletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabletAddress string `protobuf:"bytes,1,opt,name=tablet_address,json=tabletAddress,proto3" json:"tablet_address,omitempty"`
}

func (x *UnregisterTabletRequest) Reset() {
	*x = UnregisterTabletRequest{}
	mi := &file_internal_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTabletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTabletRequest) ProtoMessage() {}

func (x *UnregisterTabletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTabletRequest.ProtoReflect.Descriptor instead.
func (*UnregisterTabletRequest) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterTabletRequest) GetTabletAddress() string {
	if x != nil {
		return x.TabletAddress
	}
	return ""
}

type UnregisterTabletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnregisterTabletResponse) Reset() {
	*x = UnregisterTabletResponse{}
	mi := &file_internal_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTabletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTabletResponse) ProtoMessage() {}

func (x *UnregisterTabletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTabletResponse.ProtoReflect.Descriptor instead.
func (*UnregisterTabletResponse) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{3}
}

type ShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabletAddress string `protobuf:"bytes,1,opt,name=tablet_address,json=tabletAddress,proto3" json:"tablet_address,omitempty"`
	TableName     string `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *ShardRequest) Reset() {
	*x = ShardRequest{}
	mi := &file_internal_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRequest) ProtoMessage() {}

func (x *ShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRequest.ProtoReflect.Descriptor instead.
func (*ShardRequest) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{4}
}

func (x *ShardRequest) GetTabletAddress() string {
	if x != nil {
		return x.TabletAddress
	}
	return ""
}

func (x *ShardRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type ShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetTabletAddress string `protobuf:"bytes,1,opt,name=target_tablet_address,json=targetTabletAddress,proto3" json:"target_tablet_address,omitempty"`
}

func (x *ShardResponse) Reset() {
	*x = ShardResponse{}
	mi := &file_internal_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardResponse) ProtoMessage() {}

func (x *ShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardResponse.ProtoReflect.Descriptor instead.
func (*ShardResponse) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{5}
}

func (x *ShardResponse) GetTargetTabletAddress() string {
	if x != nil {
		return x.TargetTabletAddress
	}
	return ""
}

type ShardFinishNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string          `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Source    *TabletRowRange `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // include info about row range before and after sharding
	Target    *TabletRowRange `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *ShardFinishNotificationRequest) Reset() {
	*x = ShardFinishNotificationRequest{}
	mi := &file_internal_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardFinishNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardFinishNotificationRequest) ProtoMessage() {}

func (x *ShardFinishNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardFinishNotificationRequest.ProtoReflect.Descriptor instead.
func (*ShardFinishNotificationRequest) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{6}
}

func (x *ShardFinishNotificationRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ShardFinishNotificationRequest) GetSource() *TabletRowRange {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ShardFinishNotificationRequest) GetTarget() *TabletRowRange {
	if x != nil {
		return x.Target
	}
	return nil
}

type TabletRowRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabletAddress string `protobuf:"bytes,1,opt,name=tablet_address,json=tabletAddress,proto3" json:"tablet_address,omitempty"`
	RowFrom       string `protobuf:"bytes,2,opt,name=row_from,json=rowFrom,proto3" json:"row_from,omitempty"`
	RowTo         string `protobuf:"bytes,3,opt,name=row_to,json=rowTo,proto3" json:"row_to,omitempty"`
}

func (x *TabletRowRange) Reset() {
	*x = TabletRowRange{}
	mi := &file_internal_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabletRowRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletRowRange) ProtoMessage() {}

func (x *TabletRowRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletRowRange.ProtoReflect.Descriptor instead.
func (*TabletRowRange) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{7}
}

func (x *TabletRowRange) GetTabletAddress() string {
	if x != nil {
		return x.TabletAddress
	}
	return ""
}

func (x *TabletRowRange) GetRowFrom() string {
	if x != nil {
		return x.RowFrom
	}
	return ""
}

func (x *TabletRowRange) GetRowTo() string {
	if x != nil {
		return x.RowTo
	}
	return ""
}

type ShardFinishNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShardFinishNotificationResponse) Reset() {
	*x = ShardFinishNotificationResponse{}
	mi := &file_internal_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardFinishNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardFinishNotificationResponse) ProtoMessage() {}

func (x *ShardFinishNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardFinishNotificationResponse.ProtoReflect.Descriptor instead.
func (*ShardFinishNotificationResponse) Descriptor() ([]byte, []int) {
	return file_internal_master_proto_rawDescGZIP(), []int{8}
}

var File_internal_master_proto protoreflect.FileDescriptor

var file_internal_master_proto_rawDesc = []byte{
	0x0a, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2d, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x22, 0x3e, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x17, 0x55,
	0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1a, 0x0a,
	0x18, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x0c, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x43, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x15, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x1e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x6f, 0x77, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x69, 0x67, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x6f, 0x77, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x69, 0x0a, 0x0e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x74, 0x52, 0x6f, 0x77, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x77, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x77, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x15,
	0x0a, 0x06, 0x72, 0x6f, 0x77, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x6f, 0x77, 0x54, 0x6f, 0x22, 0x21, 0x0a, 0x1f, 0x53, 0x68, 0x61, 0x72, 0x64, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfc, 0x02, 0x0a, 0x15, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x55, 0x6e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x62, 0x69,
	0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x62, 0x69, 0x67, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x11, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x68, 0x61, 0x72, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x12, 0x28, 0x2e, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x62, 0x69, 0x67,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_master_proto_rawDescOnce sync.Once
	file_internal_master_proto_rawDescData = file_internal_master_proto_rawDesc
)

func file_internal_master_proto_rawDescGZIP() []byte {
	file_internal_master_proto_rawDescOnce.Do(func() {
		file_internal_master_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_master_proto_rawDescData)
	})
	return file_internal_master_proto_rawDescData
}

var file_internal_master_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_master_proto_goTypes = []any{
	(*RegisterTabletRequest)(nil),           // 0: bigtable.RegisterTabletRequest
	(*RegisterTabletResponse)(nil),          // 1: bigtable.RegisterTabletResponse
	(*UnregisterTabletRequest)(nil),         // 2: bigtable.UnregisterTabletRequest
	(*UnregisterTabletResponse)(nil),        // 3: bigtable.UnregisterTabletResponse
	(*ShardRequest)(nil),                    // 4: bigtable.ShardRequest
	(*ShardResponse)(nil),                   // 5: bigtable.ShardResponse
	(*ShardFinishNotificationRequest)(nil),  // 6: bigtable.ShardFinishNotificationRequest
	(*TabletRowRange)(nil),                  // 7: bigtable.TabletRowRange
	(*ShardFinishNotificationResponse)(nil), // 8: bigtable.ShardFinishNotificationResponse
}
var file_internal_master_proto_depIdxs = []int32{
	7, // 0: bigtable.ShardFinishNotificationRequest.source:type_name -> bigtable.TabletRowRange
	7, // 1: bigtable.ShardFinishNotificationRequest.target:type_name -> bigtable.TabletRowRange
	0, // 2: bigtable.MasterInternalService.RegisterTablet:input_type -> bigtable.RegisterTabletRequest
	2, // 3: bigtable.MasterInternalService.UnregisterTablet:input_type -> bigtable.UnregisterTabletRequest
	4, // 4: bigtable.MasterInternalService.NotifyShardRequest:input_type -> bigtable.ShardRequest
	6, // 5: bigtable.MasterInternalService.NotifyShardFinish:input_type -> bigtable.ShardFinishNotificationRequest
	1, // 6: bigtable.MasterInternalService.RegisterTablet:output_type -> bigtable.RegisterTabletResponse
	3, // 7: bigtable.MasterInternalService.UnregisterTablet:output_type -> bigtable.UnregisterTabletResponse
	5, // 8: bigtable.MasterInternalService.NotifyShardRequest:output_type -> bigtable.ShardResponse
	8, // 9: bigtable.MasterInternalService.NotifyShardFinish:output_type -> bigtable.ShardFinishNotificationResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_master_proto_init() }
func file_internal_master_proto_init() {
	if File_internal_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_master_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_master_proto_goTypes,
		DependencyIndexes: file_internal_master_proto_depIdxs,
		MessageInfos:      file_internal_master_proto_msgTypes,
	}.Build()
	File_internal_master_proto = out.File
	file_internal_master_proto_rawDesc = nil
	file_internal_master_proto_goTypes = nil
	file_internal_master_proto_depIdxs = nil
}
