// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: master.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterInternalService_ReportStatus_FullMethodName      = "/bigtable.MasterInternalService/ReportStatus"
	MasterInternalService_RegisterTablet_FullMethodName    = "/bigtable.MasterInternalService/RegisterTablet"
	MasterInternalService_UnregisterTablet_FullMethodName  = "/bigtable.MasterInternalService/UnregisterTablet"
	MasterInternalService_CheckShardRequest_FullMethodName = "/bigtable.MasterInternalService/CheckShardRequest"
	MasterInternalService_UpdateShard_FullMethodName       = "/bigtable.MasterInternalService/UpdateShard"
	MasterInternalService_ShardFinish_FullMethodName       = "/bigtable.MasterInternalService/ShardFinish"
)

// MasterInternalServiceClient is the client API for MasterInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterInternalServiceClient interface {
	// To notify that a tablet needs to be split
	ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error)
	// Register
	RegisterTablet(ctx context.Context, in *RegisterTabletRequest, opts ...grpc.CallOption) (*RegisterTabletResponse, error)
	UnregisterTablet(ctx context.Context, in *UnregisterTabletRequest, opts ...grpc.CallOption) (*UnregisterTabletRequest, error)
	// Sharding
	CheckShardRequest(ctx context.Context, in *ShardRequest, opts ...grpc.CallOption) (*CheckShardResponse, error)
	UpdateShard(ctx context.Context, in *UpdateShardRequest, opts ...grpc.CallOption) (*UpdateShardResponse, error)
	ShardFinish(ctx context.Context, in *ShardFinishRequest, opts ...grpc.CallOption) (*ShardFinishResponse, error)
}

type masterInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterInternalServiceClient(cc grpc.ClientConnInterface) MasterInternalServiceClient {
	return &masterInternalServiceClient{cc}
}

func (c *masterInternalServiceClient) ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusResponse)
	err := c.cc.Invoke(ctx, MasterInternalService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterInternalServiceClient) RegisterTablet(ctx context.Context, in *RegisterTabletRequest, opts ...grpc.CallOption) (*RegisterTabletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTabletResponse)
	err := c.cc.Invoke(ctx, MasterInternalService_RegisterTablet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterInternalServiceClient) UnregisterTablet(ctx context.Context, in *UnregisterTabletRequest, opts ...grpc.CallOption) (*UnregisterTabletRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterTabletRequest)
	err := c.cc.Invoke(ctx, MasterInternalService_UnregisterTablet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterInternalServiceClient) CheckShardRequest(ctx context.Context, in *ShardRequest, opts ...grpc.CallOption) (*CheckShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckShardResponse)
	err := c.cc.Invoke(ctx, MasterInternalService_CheckShardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterInternalServiceClient) UpdateShard(ctx context.Context, in *UpdateShardRequest, opts ...grpc.CallOption) (*UpdateShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShardResponse)
	err := c.cc.Invoke(ctx, MasterInternalService_UpdateShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterInternalServiceClient) ShardFinish(ctx context.Context, in *ShardFinishRequest, opts ...grpc.CallOption) (*ShardFinishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardFinishResponse)
	err := c.cc.Invoke(ctx, MasterInternalService_ShardFinish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterInternalServiceServer is the server API for MasterInternalService service.
// All implementations must embed UnimplementedMasterInternalServiceServer
// for forward compatibility.
type MasterInternalServiceServer interface {
	// To notify that a tablet needs to be split
	ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error)
	// Register
	RegisterTablet(context.Context, *RegisterTabletRequest) (*RegisterTabletResponse, error)
	UnregisterTablet(context.Context, *UnregisterTabletRequest) (*UnregisterTabletRequest, error)
	// Sharding
	CheckShardRequest(context.Context, *ShardRequest) (*CheckShardResponse, error)
	UpdateShard(context.Context, *UpdateShardRequest) (*UpdateShardResponse, error)
	ShardFinish(context.Context, *ShardFinishRequest) (*ShardFinishResponse, error)
	mustEmbedUnimplementedMasterInternalServiceServer()
}

// UnimplementedMasterInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterInternalServiceServer struct{}

func (UnimplementedMasterInternalServiceServer) ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedMasterInternalServiceServer) RegisterTablet(context.Context, *RegisterTabletRequest) (*RegisterTabletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTablet not implemented")
}
func (UnimplementedMasterInternalServiceServer) UnregisterTablet(context.Context, *UnregisterTabletRequest) (*UnregisterTabletRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterTablet not implemented")
}
func (UnimplementedMasterInternalServiceServer) CheckShardRequest(context.Context, *ShardRequest) (*CheckShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckShardRequest not implemented")
}
func (UnimplementedMasterInternalServiceServer) UpdateShard(context.Context, *UpdateShardRequest) (*UpdateShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShard not implemented")
}
func (UnimplementedMasterInternalServiceServer) ShardFinish(context.Context, *ShardFinishRequest) (*ShardFinishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShardFinish not implemented")
}
func (UnimplementedMasterInternalServiceServer) mustEmbedUnimplementedMasterInternalServiceServer() {}
func (UnimplementedMasterInternalServiceServer) testEmbeddedByValue()                               {}

// UnsafeMasterInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterInternalServiceServer will
// result in compilation errors.
type UnsafeMasterInternalServiceServer interface {
	mustEmbedUnimplementedMasterInternalServiceServer()
}

func RegisterMasterInternalServiceServer(s grpc.ServiceRegistrar, srv MasterInternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedMasterInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterInternalService_ServiceDesc, srv)
}

func _MasterInternalService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterInternalServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterInternalService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterInternalServiceServer).ReportStatus(ctx, req.(*ReportStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterInternalService_RegisterTablet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTabletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterInternalServiceServer).RegisterTablet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterInternalService_RegisterTablet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterInternalServiceServer).RegisterTablet(ctx, req.(*RegisterTabletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterInternalService_UnregisterTablet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterTabletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterInternalServiceServer).UnregisterTablet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterInternalService_UnregisterTablet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterInternalServiceServer).UnregisterTablet(ctx, req.(*UnregisterTabletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterInternalService_CheckShardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterInternalServiceServer).CheckShardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterInternalService_CheckShardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterInternalServiceServer).CheckShardRequest(ctx, req.(*ShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterInternalService_UpdateShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterInternalServiceServer).UpdateShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterInternalService_UpdateShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterInternalServiceServer).UpdateShard(ctx, req.(*UpdateShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterInternalService_ShardFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterInternalServiceServer).ShardFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterInternalService_ShardFinish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterInternalServiceServer).ShardFinish(ctx, req.(*ShardFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterInternalService_ServiceDesc is the grpc.ServiceDesc for MasterInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigtable.MasterInternalService",
	HandlerType: (*MasterInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _MasterInternalService_ReportStatus_Handler,
		},
		{
			MethodName: "RegisterTablet",
			Handler:    _MasterInternalService_RegisterTablet_Handler,
		},
		{
			MethodName: "UnregisterTablet",
			Handler:    _MasterInternalService_UnregisterTablet_Handler,
		},
		{
			MethodName: "CheckShardRequest",
			Handler:    _MasterInternalService_CheckShardRequest_Handler,
		},
		{
			MethodName: "UpdateShard",
			Handler:    _MasterInternalService_UpdateShard_Handler,
		},
		{
			MethodName: "ShardFinish",
			Handler:    _MasterInternalService_ShardFinish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
