// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: master.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterService_AssignTablet_FullMethodName         = "/bigtable.MasterService/AssignTablet"
	MasterService_UnassignTablet_FullMethodName       = "/bigtable.MasterService/UnassignTablet"
	MasterService_GetTabletAssignments_FullMethodName = "/bigtable.MasterService/GetTabletAssignments"
	MasterService_ReportTabletStatus_FullMethodName   = "/bigtable.MasterService/ReportTabletStatus"
)

// MasterServiceClient is the client API for MasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterServiceClient interface {
	AssignTablet(ctx context.Context, in *AssignTabletRequest, opts ...grpc.CallOption) (*AssignTabletResponse, error)
	UnassignTablet(ctx context.Context, in *UnassignTabletRequest, opts ...grpc.CallOption) (*UnassignTabletResponse, error)
	GetTabletAssignments(ctx context.Context, in *GetTabletAssignmentsRequest, opts ...grpc.CallOption) (*GetTabletAssignmentsResponse, error)
	ReportTabletStatus(ctx context.Context, in *ReportTabletStatusRequest, opts ...grpc.CallOption) (*ReportTabletStatusResponse, error)
}

type masterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServiceClient(cc grpc.ClientConnInterface) MasterServiceClient {
	return &masterServiceClient{cc}
}

func (c *masterServiceClient) AssignTablet(ctx context.Context, in *AssignTabletRequest, opts ...grpc.CallOption) (*AssignTabletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignTabletResponse)
	err := c.cc.Invoke(ctx, MasterService_AssignTablet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) UnassignTablet(ctx context.Context, in *UnassignTabletRequest, opts ...grpc.CallOption) (*UnassignTabletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignTabletResponse)
	err := c.cc.Invoke(ctx, MasterService_UnassignTablet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) GetTabletAssignments(ctx context.Context, in *GetTabletAssignmentsRequest, opts ...grpc.CallOption) (*GetTabletAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTabletAssignmentsResponse)
	err := c.cc.Invoke(ctx, MasterService_GetTabletAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) ReportTabletStatus(ctx context.Context, in *ReportTabletStatusRequest, opts ...grpc.CallOption) (*ReportTabletStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTabletStatusResponse)
	err := c.cc.Invoke(ctx, MasterService_ReportTabletStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServiceServer is the server API for MasterService service.
// All implementations must embed UnimplementedMasterServiceServer
// for forward compatibility.
type MasterServiceServer interface {
	AssignTablet(context.Context, *AssignTabletRequest) (*AssignTabletResponse, error)
	UnassignTablet(context.Context, *UnassignTabletRequest) (*UnassignTabletResponse, error)
	GetTabletAssignments(context.Context, *GetTabletAssignmentsRequest) (*GetTabletAssignmentsResponse, error)
	ReportTabletStatus(context.Context, *ReportTabletStatusRequest) (*ReportTabletStatusResponse, error)
	mustEmbedUnimplementedMasterServiceServer()
}

// UnimplementedMasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterServiceServer struct{}

func (UnimplementedMasterServiceServer) AssignTablet(context.Context, *AssignTabletRequest) (*AssignTabletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTablet not implemented")
}
func (UnimplementedMasterServiceServer) UnassignTablet(context.Context, *UnassignTabletRequest) (*UnassignTabletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignTablet not implemented")
}
func (UnimplementedMasterServiceServer) GetTabletAssignments(context.Context, *GetTabletAssignmentsRequest) (*GetTabletAssignmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTabletAssignments not implemented")
}
func (UnimplementedMasterServiceServer) ReportTabletStatus(context.Context, *ReportTabletStatusRequest) (*ReportTabletStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTabletStatus not implemented")
}
func (UnimplementedMasterServiceServer) mustEmbedUnimplementedMasterServiceServer() {}
func (UnimplementedMasterServiceServer) testEmbeddedByValue()                       {}

// UnsafeMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServiceServer will
// result in compilation errors.
type UnsafeMasterServiceServer interface {
	mustEmbedUnimplementedMasterServiceServer()
}

func RegisterMasterServiceServer(s grpc.ServiceRegistrar, srv MasterServiceServer) {
	// If the following call pancis, it indicates UnimplementedMasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterService_ServiceDesc, srv)
}

func _MasterService_AssignTablet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTabletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).AssignTablet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_AssignTablet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).AssignTablet(ctx, req.(*AssignTabletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_UnassignTablet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignTabletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).UnassignTablet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_UnassignTablet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).UnassignTablet(ctx, req.(*UnassignTabletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_GetTabletAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTabletAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).GetTabletAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_GetTabletAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).GetTabletAssignments(ctx, req.(*GetTabletAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_ReportTabletStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTabletStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).ReportTabletStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_ReportTabletStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).ReportTabletStatus(ctx, req.(*ReportTabletStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterService_ServiceDesc is the grpc.ServiceDesc for MasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigtable.MasterService",
	HandlerType: (*MasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignTablet",
			Handler:    _MasterService_AssignTablet_Handler,
		},
		{
			MethodName: "UnassignTablet",
			Handler:    _MasterService_UnassignTablet_Handler,
		},
		{
			MethodName: "GetTabletAssignments",
			Handler:    _MasterService_GetTabletAssignments_Handler,
		},
		{
			MethodName: "ReportTabletStatus",
			Handler:    _MasterService_ReportTabletStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
