// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: external-master.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterExternalService_CreateTable_FullMethodName       = "/bigtable.MasterExternalService/CreateTable"
	MasterExternalService_DeleteTable_FullMethodName       = "/bigtable.MasterExternalService/DeleteTable"
	MasterExternalService_GetTabletLocation_FullMethodName = "/bigtable.MasterExternalService/GetTabletLocation"
)

// MasterExternalServiceClient is the client API for MasterExternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterExternalServiceClient interface {
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error)
	GetTabletLocation(ctx context.Context, in *GetTabletLocationRequest, opts ...grpc.CallOption) (*GetTabletLocationResponse, error)
}

type masterExternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterExternalServiceClient(cc grpc.ClientConnInterface) MasterExternalServiceClient {
	return &masterExternalServiceClient{cc}
}

func (c *masterExternalServiceClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, MasterExternalService_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterExternalServiceClient) DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTableResponse)
	err := c.cc.Invoke(ctx, MasterExternalService_DeleteTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterExternalServiceClient) GetTabletLocation(ctx context.Context, in *GetTabletLocationRequest, opts ...grpc.CallOption) (*GetTabletLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTabletLocationResponse)
	err := c.cc.Invoke(ctx, MasterExternalService_GetTabletLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterExternalServiceServer is the server API for MasterExternalService service.
// All implementations must embed UnimplementedMasterExternalServiceServer
// for forward compatibility.
type MasterExternalServiceServer interface {
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	DeleteTable(context.Context, *DeleteTableRequest) (*DeleteTableResponse, error)
	GetTabletLocation(context.Context, *GetTabletLocationRequest) (*GetTabletLocationResponse, error)
	mustEmbedUnimplementedMasterExternalServiceServer()
}

// UnimplementedMasterExternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterExternalServiceServer struct{}

func (UnimplementedMasterExternalServiceServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedMasterExternalServiceServer) DeleteTable(context.Context, *DeleteTableRequest) (*DeleteTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTable not implemented")
}
func (UnimplementedMasterExternalServiceServer) GetTabletLocation(context.Context, *GetTabletLocationRequest) (*GetTabletLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTabletLocation not implemented")
}
func (UnimplementedMasterExternalServiceServer) mustEmbedUnimplementedMasterExternalServiceServer() {}
func (UnimplementedMasterExternalServiceServer) testEmbeddedByValue()                               {}

// UnsafeMasterExternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterExternalServiceServer will
// result in compilation errors.
type UnsafeMasterExternalServiceServer interface {
	mustEmbedUnimplementedMasterExternalServiceServer()
}

func RegisterMasterExternalServiceServer(s grpc.ServiceRegistrar, srv MasterExternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedMasterExternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterExternalService_ServiceDesc, srv)
}

func _MasterExternalService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterExternalServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterExternalService_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterExternalServiceServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterExternalService_DeleteTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterExternalServiceServer).DeleteTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterExternalService_DeleteTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterExternalServiceServer).DeleteTable(ctx, req.(*DeleteTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterExternalService_GetTabletLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTabletLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterExternalServiceServer).GetTabletLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterExternalService_GetTabletLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterExternalServiceServer).GetTabletLocation(ctx, req.(*GetTabletLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterExternalService_ServiceDesc is the grpc.ServiceDesc for MasterExternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterExternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigtable.MasterExternalService",
	HandlerType: (*MasterExternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTable",
			Handler:    _MasterExternalService_CreateTable_Handler,
		},
		{
			MethodName: "DeleteTable",
			Handler:    _MasterExternalService_DeleteTable_Handler,
		},
		{
			MethodName: "GetTabletLocation",
			Handler:    _MasterExternalService_GetTabletLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "external-master.proto",
}
